### ISSUE TITLE
Hardware setup

### ISSUE THREAD

**Issue by acorbin3** [AdamCorbinFAUPhD/CEN5035-Software-Engineering-Course-Project#13]
- [x] Webcamera
- [x] Keypad
- [x] LED for warning
- [x] PIS motion sensor
~~Speaker/Buzzer. Removed due to time constraints~~
- [x] Document this in the final report

**Comment by acorbin3** [comment]
Question, for the LED should we have a Green one and red one for when it gets tripped?

**Comment by JaredEdu** [comment]
yes I say that sounds reasonable
