### ISSUE TITLE
Google Calendar schedule for Alarm

### ISSUE THREAD

**Issue by acorbin3** [AdamCorbinFAUPhD/CEN5035-Software-Engineering-Course-Project#21]
- [x] Connect up to google calendar to read 
- [x] Arm and disarm based on google calendar
- [x] Add documentation
- [x] Add testing?

**Comment by acorbin3** [comment]
Due to time constraints we are going to assume all events mean they are away

**Comment by JaredEdu** [comment]
I did some testing of the logic tonight and it seems to work. We can write test cases but I think we need to keep pressing forward.
