### ISSUE TITLE
Video/Screenshot capture

### ISSUE THREAD

**Issue by acorbin3** [AdamCorbinFAUPhD/CEN5035-Software-Engineering-Course-Project#22]
This covers when an alarm is triggered to get a screenshot or record video. The follow items are in priority order
- [x] Capture Screenshot
- [x] Store screenshot on raspberry Pi
- [x] view live stream.
- [x] record live stream

**Comment by acorbin3** [comment]
Found out that you can take a snapshot by just going to this address: http://adamcorbin.com:8080/0/action/snapshot

Then they get stored here: /var/lib/motion
Looks like we can change this destination based on the config. Here is a link on this info: https://raspberrypi.stackexchange.com/a/72767

**Comment by acorbin3** [comment]
This might be useful in creating videos. It looks like this motion lib is really used when there is some kind of detection and if its not present then no video is recorded. 

https://raspberrypi.stackexchange.com/questions/38469/recording-video-using-motion-regardless-of-motion-detection

**Comment by JaredEdu** [comment]
finished! added all features to camera.py and added calls to the system API
